// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "api.h"
#include "spdlog/spdlog.h"
#include "Huffman.h"

std::string api::echo(const std::string& text)
{
    return "Hi, " + text;
}

std::string api::addSequence(const std::string& sequence)
{
    spdlog::info("Enter in addSequence, {}!", sequence);
    Huffman huffman = Huffman(sequence);
    std::string compresed = huffman.Encode();
    spdlog::info("Encoded sequence is {}!", compresed);

    return compresed;
}

